name: Bandit Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  process_bandit_output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Install dependencies
        run: pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit_output.json || true
          cat bandit_output.json  # Display Bandit output

       
      - name: Parse Bandit output JSON
        run: |
          # Parse Bandit output JSON
          bandit_output=$(<bandit_output.json)
          # Extract counts of HIGH and MEDIUM vulnerabilities using jq
          high_count=$(echo "$bandit_output" | jq '[.metrics[] | .["SEVERITY"]["HIGH"] // 0] | add')
          medium_count=$(echo "$bandit_output" | jq '[.metrics[] | .["SEVERITY"]["MEDIUM"] // 0] | add')
          # Check if HIGH or MEDIUM count is greater than 0
          if (( high_count > 0 )) || (( medium_count > 0 )); then
              echo "Critical or High vulnerability found! Blocking commit."
              exit 1
          else
              echo "No critical or high vulnerabilities found. Commit allowed."
          fi
