name: Bandit Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  process_bandit_output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit_output.json || true
          cat bandit_output.json  # Display Bandit output

      - name: Parse Bandit output JSON and add comment
        run: |
          # Parse Bandit output JSON
          bandit_output=$(<bandit_output.json)
          # Extract counts of HIGH and MEDIUM vulnerabilities using jq
          high_count=$(echo "$bandit_output" | jq '[.results[] | select(.issue_severity == "HIGH")] | length')
          medium_count=$(echo "$bandit_output" | jq '[.results[] | select(.issue_severity == "MEDIUM")] | length')
          # Check if HIGH or MEDIUM count is greater than 0
          if [ "$high_count" -gt 0 ] || [ "$medium_count" -gt 0 ]; then
              echo "Critical or High vulnerability found! Blocking commit."
              comment="Block"
          else
              echo "No critical or high vulnerabilities found. Commit allowed."
              comment="Successful"
          fi
          # Add comment to the pull request
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments" \
            -d "{\"body\":\"$comment\"}"
