name: Bandit Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit_output.txt || true
          cat bandit_output.txt  # Display Bandit output
          
      - name: Check for critical vulnerabilities
        run: |
          grep -E "Critical|High" bandit_output.txt
          if [ $? -eq 0 ]; then
            echo "Critical or High vulnerability found! Blocking pull request."
            exit 1
          fi

      - name: Get repository information
        id: repo_info
        run: |
          echo "::set-output name=user::${{ github.repository_owner }}"
          echo "::set-output name=repo::${{ github.repository_name }}"

      - name: Comment and Block Pull Request (if critical found)
        run: |
          comment="Block"
          headers = {
          'Authorization': 'Bearer ${{ secrets.GITHUB_TOKEN }}',
          'Accept': 'application/vnd.github.v3+json'
          }
          data = {
          'body': comment
          }
          response = requests.post('https://api.github.com/repos/${{ steps.repo_info.outputs.user }}/${{ steps.repo_info.outputs.repo }}/issues/${{ github.event.issue.number }}/comments', headers=headers, json=data)
          print(response.text)
          if: failure()

      - name: Comment and Auto-Merge Pull Request (if successful)
        run: |
          comment="Successful"
          headers = {
          'Authorization': 'Bearer ${{ secrets.GITHUB_TOKEN }}',
          'Accept': 'application/vnd.github.v3+json'
          }
          data = {
          'body': comment
          }
          response = requests.post('https://api.github.com/repos/${{ steps.repo_info.outputs.user }}/${{ steps.repo_info.outputs.repo }}/issues/${{ github.event.issue.number }}/comments', headers=headers, json=data)
          print(response.text)
          if: success()
