name: Bandit Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit_output.json || true
          cat bandit_output.json  # Display Bandit output
          
      - name: Check for critical vulnerabilities
        run: |
          #!/bin/bash
          # Parse Bandit output JSON
          bandit_output=$(<bandit_output.json)
          # Iterate over all files and check vulnerability counts
          while IFS= read -r line; do
            if [[ $line == *"SEVERITY.HIGH"* ]]; then
              file_path=$(echo "$line" | jq -r 'keys[]')
              critical_count=$(echo "$line" | jq -r '.SEVERITY.HIGH')
              high_count=$(echo "$line" | jq -r '.SEVERITY.MEDIUM')
            if (( critical_count > 0 )) || (( high_count > 0 )); then
              echo "Critical or High vulnerability found in file: $file_path"
              exit 1
            fi
            fi
            done <<< "$(echo "$bandit_output" | jq -r '.metrics | to_entries[] | .value')"
          exit 0
      
      - name: Get repository information
        id: repo_info
        run: |
          echo "::set-output name=user::${{ github.repository_owner }}"
          echo "::set-output name=repo::${{ github.repository_name }}"

      - name: Comment and Block Pull Request (if critical found)
        run: |
          comment="Block"
          headers = {
          'Authorization': 'Bearer ${{ secrets.GITHUB_TOKEN }}',
          'Accept': 'application/vnd.github.v3+json'
          }
          data = {
          'body': comment
          }
          response = requests.post('https://api.github.com/repos/${{ steps.repo_info.outputs.user }}/${{ steps.repo_info.outputs.repo }}/issues/${{ github.event.issue.number }}/comments', headers=headers, json=data)
          print(response.text)
          if: failure()

      - name: Comment and Auto-Merge Pull Request (if successful)
        run: |
          comment="Successful"
          headers = {
          'Authorization': 'Bearer ${{ secrets.GITHUB_TOKEN }}',
          'Accept': 'application/vnd.github.v3+json'
          }
          data = {
          'body': comment
          }
          response = requests.post('https://api.github.com/repos/${{ steps.repo_info.outputs.user }}/${{ steps.repo_info.outputs.repo }}/issues/${{ github.event.issue.number }}/comments', headers=headers, json=data)
          print(response.text)
          if: success()
