name: Bandit Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit_output.json || true
          cat bandit_output.json  # Display Bandit output
          
      - name: Check for critical vulnerabilities
        run: |
          # Parse Bandit output JSON
          import json

          with open('bandit_output.json') as f:
          bandit_output = json.load(f)

          # Iterate over all files and check vulnerability counts
          for file_path, metrics in bandit_output['metrics'].items():
          critical_count = metrics['SEVERITY.HIGH']
          high_count = metrics['SEVERITY.MEDIUM']

          if critical_count > 0 or high_count > 0:
            echo "Critical or High vulnerability found in file: $file_path"
          exit 1

      - name: Get repository information
        id: repo_info
        run: |
          echo "::set-output name=user::${{ github.repository_owner }}"
          echo "::set-output name=repo::${{ github.repository_name }}"

      - name: Comment and Block Pull Request (if critical found)
        run: |
          comment="Block"
          headers = {
          'Authorization': 'Bearer ${{ secrets.GITHUB_TOKEN }}',
          'Accept': 'application/vnd.github.v3+json'
          }
          data = {
          'body': comment
          }
          response = requests.post('https://api.github.com/repos/${{ steps.repo_info.outputs.user }}/${{ steps.repo_info.outputs.repo }}/issues/${{ github.event.issue.number }}/comments', headers=headers, json=data)
          print(response.text)
          if: failure()

      - name: Comment and Auto-Merge Pull Request (if successful)
        run: |
          comment="Successful"
          headers = {
          'Authorization': 'Bearer ${{ secrets.GITHUB_TOKEN }}',
          'Accept': 'application/vnd.github.v3+json'
          }
          data = {
          'body': comment
          }
          response = requests.post('https://api.github.com/repos/${{ steps.repo_info.outputs.user }}/${{ steps.repo_info.outputs.repo }}/issues/${{ github.event.issue.number }}/comments', headers=headers, json=data)
          print(response.text)
          if: success()
